  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_1_to_arm_base
    pid: {p: 10, i: 0.0, d: 0.0}

    
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_to_arm_base
    pid: {p: 1.0, i: 0.0, d: 0.0}
    
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_2_to_arm_1
    pid: {p: 1, i: 0.0, d: 0.0}
    
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_3_to_arm_2
    pid: {p: 1, i: 0.0, d: 0.0}


